name: plant_identify_care
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:

  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  http: any
  lottie: ^2.4.0
  percent_indicator: ^4.2.3
  rive: ^0.9.1
  velocity_x: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/RiveAssets/
    - assets/lottie/
    - assets/illustration/
    - assets/icons/
    - .env
    - assets/fonts/

  fonts:
    - family: Allura
      fonts:
        - asset: assets/fonts/Allura-Regular.ttf
